import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { ModeToggle } from "../components/ui/DarkmodeToggle";
import { cn } from "@/lib/utils";
import { SidebarProvider, SidebarTrigger } from "../components/ui/sidebar";
import { AppSidebar } from "../components/AppSidebar";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("h-full", "w-full", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
      <body className="min-h-full w-full grid grid-cols-23 grid-rows-23">
        <ThemeProvider attribute={"class"} defaultTheme="system" enableSystem>
          <div className="grid row-start-1 row-end-2 col-start-24 col-end-24">
          <ModeToggle />
          </div>
          <SidebarProvider>
      <AppSidebar />
      <main>
        <SidebarTrigger />
        {children}
      </main>
    </SidebarProvider>
          </ThemeProvider></body>
    </html>
  );
}
